### ISSUE TITLE
Show Arok's notes on divvunspell suggestions

### ISSUE THREAD

**Issue by nienna73** [UAlbertaALTLab/recording-validation-interface#120]
Sometimes there are useful notes in Arok's dictionary that could provide further insight into the spelling suggestions provided by `divvunspell`. These notes can indicate things like spelling variations, so showing the notes would be useful.

This should be done with either a new page or a pop-up view.

Where and how do we access these notes?

**Comment by aarppe** [comment]
Currently, the latest version of Arok's toolbox files is in our ALTLab repo:

`./altlab/crk/dicts/Wolvengrey.toolbox
`
Right now, I manually fetch updates of this file, but on the longer term we might want to automate the process - that would require a bit of planning.

This is the list of all fields in this CW database:

```
cat ~/altlab2/crk/dicts/Wolvengrey.toolbox | cut -f1 -d" " | sort | uniq -c | sort -nr
72984 \gl
67733 \mrp
22868 \alt
22242 \sem
21950 \rel
21925 \def
21740 \stm
21728 \ps
21727 \dl
21718 \his
21717 \gr1
21716 \syl
21716 \sro
21716 \dt
21715 \gr2
21714 \cat
21648 \drv
10817 \src
5337 \new
 412 \??
  10 \altsp
   1 \_sh
```
I could imagine that one could allow for presenting all this information, e.g. in a pop-up (perhaps leaving out those fields per record that do not have a value).

**Comment by nienna73** [comment]
This task is going to take a relatively large amount of time for me to implement and hasn't been brought up since it was initially thought of 6 months ago. Is this something I should continue to keep on my backburner, or should we mark it as a `wontfix` and close it?

**Comment by aarppe** [comment]
While it would be neat to have all this information at one's fingertips within the same interface, I think we concluded as a perfectly sufficient interim measure that the intended goal can be achieved if the linguist validator has access to Arok's database (which should be the case) and can look up all that information themselves separately, rather than spending an inordinate amount of time in coding this - it will likely be much better implemented with an interface into our ALTLab crk dictionary dataabase, which Danny would be working on, whenever that will happen.
