### ISSUE TITLE
Add fields to Speaker: bio (eng + crk), picture, and anonymous

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/recording-validation-interface#35]
Should extend the `Speaker` model with a few more fields:

 - bio
 - picture: media
 - anonymous: bool (or !consented_to_identification)

The `recording/_search` API will have to be changed accordingly.

**Comment by aarppe** [comment]
Speaker names and genders entered in validation app for most speakers. There were two not-known speaker codes (JON and MAL), but I will sort these out. Nevertheless, this means that the recordings for all the other speakers in the currently processed recordings materials should be incorporable in itwêwina.

**Comment by aarppe** [comment]
Concerning the title, we have discussed with Rose having terse bios in both Cree and English (When we get those is another matter).

**Comment by aarppe** [comment]
An HTML table with speakers in the order of descending number of sessions participated, and pictures for most of the them, is available in our project GDrive:

file:///Users/arppe/Google%20Drive/CreeFST/Maskwacis/Speakers/index.html
file:///Users/arppe/Google%20Drive/CreeFST/Maskwacis/Speakers/

Clicking on a speaker name takes to the image, as we don't have any bios yet.

I tried a bit of formatting (width="300") just so that the current version is examinable, but didn't bother with anything more, if/when we are going to make these available through the validation app.

**Comment by nienna73** [comment]
This task is about 60% done. Remaining items are:

- [x] make speaker image a file/media field
- [x] implemented Anonymous attribute
- [x] redirect itwêwina to the speakers page in speech-db
