### ISSUE TITLE
Relax vowel length matching

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/recording-validation-interface#37]

**Comment by aarppe** [comment]
Is this the reason why e.g. pwâwîw which has recordings in the validation interface does not show up in itwêwina? On the other hand, iskwêsis does show up in both!?

**Comment by aarppe** [comment]
Generally, some forms in the validation app do appear as expected as audio snippets in itwêwina, whereas other do not, even though one would expect so.

Some examples of not entirely systematic matching of recording snippet transcriptions and normative lemmas generated according to the CW-based FST:

1. Accessible in validation app, but not at all in itwêwina:

kostâcinâkosiw

2. Accessible as inflected form in validation app, and analyzed properly in itwêwina, but not provided as a listed inflected audio form in itwêwina:

kisêhkimaw (<- sêkimêw) [field transcription has aspiration, whereas CW does not]

3. Accessible as inflected form in validation app, and providing linguistic analysis but not providing match with lexical entry (whether in MD or CW) (nor provided as an inflected audio form):

kikostihk (<- kostêw)
kikostew (<- kostêw)

4. Accessible as inflected form in validation app, and matching correct lexical entry in itwêwina, and listed correctly among inflected audio forms.

kikostên (<- kostam)

Very desirable behavior (4) illustrated in screen shot below:

![image](https://user-images.githubusercontent.com/15003407/50144570-ce289380-026c-11e9-8a75-eeeb4a7b8d1c.png)


CONCLUSION: Validation app needs to allow for the specification of the lemma of any recorded form, so that inflected audio forms can be grouped and presented together under the same lemma. Suggestions for lemmas can be provided the descriptive FST.

**Comment by eddieantonio** [comment]
> Is this the reason why e.g. pwâwîw which has recordings in the validation interface does not show up in itwêwina? On the other hand, iskwêsis does show up in both!?

The reason this happens is because, when a transcription is stored in the validation interface, it assumes the text is an crk phrase written in SRO. Since, <ê> is _always_ long, any <e>s are converted to <ê>. <ê> is always long. <e> is never stored. There are some other normalizations applied like trimming whitespace and ensuring ever letter is lowercase.

As a result, <iskwêwsis>, having only <ê> in it, matches what's in the database exactly, as it was stored as <iskwêwsis> even if it was originally typed as < Iskwewsis>. However, <pwawow> will be normalized to <pwawow>, and itwêwina looks up for <pwâwîw>, and will fail to come up with an exact match.

There is _one_ hack I implemented, however. The validation interface will remove the hyphen in PV/e+Cnj when searching for recordings, since the transcriptions in the database tend to lack the hyphen.

**Comment by eddieantonio** [comment]
By the way, these are the word forms that are matched when querying for a recording:

```python
# This is a list of the tags of suitable word forms for parts of speech -- mostly verbs.
SUITABLE_WORD_FORMS = {
    # VAI/VTI forms
    (u'V', u'AI', u'Ind', u'Prs', u'1Sg'),
    (u'V', u'TI', u'Ind', u'Prs', u'1Sg'),
    (u'V', u'AI', u'Ind', u'Prs', u'3Sg'),
    (u'V', u'TI', u'Ind', u'Prs', u'3Sg'),
    (u'PV/e', u'V', u'AI', u'Cnj', u'Prs', u'3Sg'),
    (u'PV/e', u'V', u'TI', u'Cnj', u'Prs', u'3Sg'),
    # VII forms
    (u'V', u'II', u'Ind', u'Prs', u'3Sg'),
    (u'PV/e', u'V', u'II', u'Cnj', u'Prs', u'3Sg'),
    # VTA forms
    (u'V', u'TA', u'Ind', u'Prs', u'1Sg', u'2SgO'),
    (u'V', u'TA', u'Ind', u'Prs', u'3Sg', u'4Sg/PlO'),
    (u'PV/e', u'V', u'TA', u'Cnj', u'Prs', u'X', u'3SgO'),
    # TODO: NID/NAD forms
}
```

2s → 3s is not in there, so it'll never be found regardless. The lemma thing (#39) is a good idea to implement! itwêwina would ask, "what recordings do you have for this lemma?" and the validation app would reply with ALL OF THE FORMS it is aware of.

**Comment by aarppe** [comment]
Yes, if/when we have the recording snippets of inflected forms linked to a lemma, then we would want to present all such audio snippets - and we wouldn't have to go after selected forms as above.

**Comment by eddieantonio** [comment]
`recval` now relaxes vowel lengths, as well as some other normalizations when searching for recordings. Consequently, some more recordings are available in itwêwina!

Try:

 - [pwâwîw](http://altlab.ualberta.ca/itwewina/crk/eng/?lookup=pw%C3%A2w%C3%AEw)
 - [kostâcinâkosiw](http://altlab.ualberta.ca/itwewina/crk/eng/?lookup=kost%C3%A2cin%C3%A2kosiw) (by the way, that voice does _not_ sound like Rosie!)
 - [iskwêwsis](http://altlab.ualberta.ca/itwewina/crk/eng/?lookup=iskw%C3%AAsis)
