### ISSUE TITLE
Add not-reviewed to status (in advanced search)

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#460]
Currently, there does not appear to be an easy way to find all entries which are not-reviewed, i.e. having red (or gray or green) in the top bar. This might lead to modifying the various types of status that the entries currently have.

**Comment by fbanados** [comment]
Also check if there's a separate way to distinguish something that has not been human validated.

**Comment by fbanados** [comment]
"Transcription / Translation validated"

**Comment by fbanados** [comment]
Also clarify what the "Filter by" options do mean and make it clear for users.

**Comment by fbanados** [comment]
> Also check if there's a separate way to distinguish something that has not been human validated.

"New" plus "Auto-Validated" should count for that.

**Comment by fbanados** [comment]
> Also clarify what the "Filter by" options do mean and make it clear for users.

I will be adding documentation on hover for these, at least when in advanced search:
![Screenshot 2024-10-03 at 10 10 29 AM](https://github.com/user-attachments/assets/c47f5d59-724a-483f-9381-5acd4b3c25aa)

**Comment by fbanados** [comment]
Advanced search has been updated and deployed to solve this issues.  Also, filtering by speaker has performance improvements by refactoring query so that django can make more use of SQL instead of manipulating python lists of results.

Also added a "Grey card" option to show only results with a grey card.

Finally, hovering on the color marker of a result entry explains why the card is marked that way (documentation):

Either green:
![Screenshot 2024-10-03 at 12 34 13 PM](https://github.com/user-attachments/assets/cd6d5ef9-d10f-4719-8ff3-a308c128f442)

Or red:
![Screenshot 2024-10-03 at 12 34 30 PM](https://github.com/user-attachments/assets/627675b5-6e4e-43e0-a5f9-b1116a921a17)

Or grey:
![Screenshot 2024-10-03 at 12 34 57 PM](https://github.com/user-attachments/assets/c7b4e154-fba3-48af-bc4e-7220730dd8c4)

Also added a reminder of *why* does an "Approve or Use" button appear some times:  Entries that are User submitted must be approved for use before being included in, for example, morphodict results.

![Screenshot 2024-10-03 at 12 36 11 PM](https://github.com/user-attachments/assets/b2db21d8-6ed1-4838-a226-2754e045da3e)
