### ISSUE TITLE
[API] Return the matched search string

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/recording-validation-interface#75]
Let's say you search for two wordforms: `wâpamêw` and `ê-wâpamât`:

```HTTP
GET /recording/_search/wâpamêw,ê-wâpamat
```

You'll get a list of results, however, **none of the results say which wordform they matched with**:

```JSON
[
  {
    "wordform": "wapamew",
    "speaker": "MAR",
    "speaker_name": "Mary Jean Littlechild",
    "anonymous": false,
    "gender": "F",
    "recording_url": "http://sapir.artsrn.ualberta.ca/validation/recording/e44429dafbd1a5d1996f784a8d22ea05006c75ffeea469337109dc8a15904789.m4a"
  }
]
```

**Note**: `wordform` here lists the text found in the database — which we should not trust!

---

**Proposal**:

Add the **matched wordform** (i.e., what was in the search string) to each search result:

```json
[
  {
    "wordform": "wapamew",
    "matched_wordform": "wâpamêw",
    "speaker": "MAR",
    "speaker_name": "Mary Jean Littlechild",
    "anonymous": false,
    "gender": "F",
    "recording_url": "http://sapir.artsrn.ualberta.ca/validation/recording/e44429dafbd1a5d1996f784a8d22ea05006c75ffeea469337109dc8a15904789.m4a"
  }
]
```

This will make it super easy to associate recordings with wordforms in users of the API, and for the users of the API to provide their own spelling.

---

Try the search here: http://sapir.artsrn.ualberta.ca/validation/recording/_search/w%C3%A2pam%C3%AAw,%C3%AA-w%C3%A2pamat

**Comment by aarppe** [comment]
So that itwêwina or another application sends to the lexical database are standardized inflected forms, which the validation app simplifies trying to match recordings and their annotations, but which matches can be rematched with the standardized inflected word forms that were used in the search, and then shown to the user, instead of the simplified forms. This should work for now, and eventually come up with something more precise (to avoid false matches of the _nipihk_ type).
