### ISSUE TITLE
Implement a Login interface

### ISSUE THREAD

**Issue by nienna73** [UAlbertaALTLab/recording-validation-interface#92]
The user should be able to login using a unique and identifying username.
For additional security, the user could also be asked to create a password for their account.

The purpose of having someone login is so we can keep track of who is making edits to entries. This could help with the validation process, but more likely will help us know who to contact if we have questions.

I've come up with a few different login options, as depicted below:
<img width="436" alt="login" src="https://user-images.githubusercontent.com/28357720/103038301-5b251800-452b-11eb-9197-0d7c8d091e48.png">

**Option 1:** Force all users to login before proceeding. This option could potentially block people from viewing the entries without a username, and I don't think that's what we want to do. The login page would be the first thing anyone visiting the site would see and all other features (mainly search) would be disabled until the user logs in.

**Option 2:** Persistent login field in the sidebar. This option allows the user to view all functionality without having to log in, but the option to log in is always available on the side. The user would be forced to log in before making any edits.

**Option 3:** Login button in the header. The user would be brought to the page as it currently exists when they visit the site, the only difference being a "login" button in the upper portion of the screen. A user can login whenever they please and will be forced to login before making any edits.

**Unanswered questions:**
- Can users continue as a guest? That is, can someone make edits to an entry without an account?

No matter the option chosen, a form of username database will be necessary to keep track of who is making edits and who is registered with the site.

**Comment by eddieantonio** [comment]
Relevant docs: https://docs.djangoproject.com/en/2.2/topics/auth/

(some vacation, eh?)

**Comment by aarppe** [comment]
Ideally, the interface to the speech database would allow for non-validators, such as language instructors or learners, to look up for spoken materials for whichever pedagogical use - so that need not require user authentication. Whether such searching is best done within the same interface as the validation/standardization can be discussed, of course.

For editing existing content, one would have to be a known user. And otherwise as well, I'd imagine that even if we'd allow for people to upload new recording snippets, we'd still want to know who they are, for crediting and reliability reasons. This could be different if we'd want to support the general standardization and validation of materials which have not been collected by us.

**Comment by nienna73** [comment]
Login functionality has been implemented as described above. Users can see all entries and search for entries without being logged in, but must log in before making edits.
