### ISSUE TITLE
Calculate MED

### ISSUE THREAD

**Issue by nienna73** [UAlbertaALTLab/recording-validation-interface#99]
When presented with a word from the database and a suggested word from another service, the system should be able to calculate the Mean Edit Distance (MED) between the two spellings.

MED is defined as the following in Issue #91 :

- adding/removing diacritics or hyphens, swapping glides w/y, or adding/removing aspirations -h- between vowel and consonant would have a weight of zero.
- inserting the vowel -i- between two consonants would have a half-weight (0.5).
- inserting/removing/swapping any other characters would have a normal weight of one.

Is this something the service has to do itself, or do one of the other services (hfst, divvunspell) provide the MED?

**Comment by eddieantonio** [comment]
@aarppe is there a weighted FST that does this? Is this part done within the spell checker (so we can use `divvunspell`)?

**Comment by nienna73** [comment]
MED is calculated using a combination of divvunspell for the spelling suggestions and difflib to find the differences between the suggestions and the original word. There's then a whole bunch of python that goes on to find the exact types of differences and calculate MED following the rules above.

There will soon be a PR that covers this issue, but I'm blocked by divvunspell. The python SDK isn't yet on PyPI so I can only run the divvunspell portion locally. I should also write some tests.

Question: divvunspell needs a .zhfst file to run. Is this something we typically include in Git, or will we have to manually add it to the server?

**Comment by aarppe** [comment]
`crk.zhfst` is generated in `giellalt/lang-crk` with the option `./configure --enable-spellers`, and is to be found in `giellalt/lang-crk/tools/spellcheckers/`.

**Comment by nienna73** [comment]
@aarppe I get that we have to build it locally using those steps, but how do we build it for the production server?
Do we follow those same steps on Sapir, or do we include the `.zhfst` file in the Git repo?

**Comment by aarppe** [comment]
We haven't included compiling `crk.zhfst` in our own regular compilation scheme, and reconstructing all the stages might not be worth the effort right now, or even later.

For the time being, we might just build manually `crk.zhfst` and store that wherever it's convenient.

On the longer term, we might want to automate that process, since we might be adding gradually new lexemes to the core FST while we're reviewing the Maskwacîs recordings content (i.e. the manually identifed lemmas that I've noted in the previous specs), and it would be good to recognize those properly in the validation interface.
